name: curiosity
description: Demonstrates how to use the curiosity plugin.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_curiosity:
    path: ../
  flutter_waya: ^7.0.0
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true