name: curiosity
description: Demonstrates how to use the curiosity plugin.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^5.0.0+hotfix.3
  camera: ^0.5.8+17
  flutter_curiosity:
    path: ../
  flutter_waya:
    path: ../../flutter_waya

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
