name: curiosity
description: Demonstrates how to use the curiosity plugin.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_curiosity:
    path: ../
  flutter_waya: ^8.0.3
  permission_handler: ^10.4.3
  file_picker: ^5.5.0

dev_dependencies:
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true