name: curiosity
description: Demonstrates how to use the curiosity plugin.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_curiosity:
    path: ../
  fl_extended: ^1.5.0
  permission_handler: ^11.3.1
  file_picker: ^8.1.1

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true