name: curiosity
description: Demonstrates how to use the curiosity plugin.
publish_to: 'none'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  permission_handler: ^5.0.0+hotfix.3
  flutter_waya:
    git:
      url: git://github.com/Wayaer/flutter_waya.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_curiosity:
    path: ../


flutter:

  uses-material-design: true
