name: curiosity
description: Demonstrates how to use the curiosity plugin.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.1 <3.0.0'

dependencies:
  camera: ^0.8.1
  flutter:
    sdk: flutter
  flutter_curiosity:
    path: ../
  flutter_waya: ^1.10.1
  permission_handler: ^7.1.0

flutter:
  uses-material-design: true