name: curiosity
description: Demonstrates how to use the curiosity plugin.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_curiosity:
    path: ../
  flutter_waya: ^1.13.2
  permission_handler: ^8.1.4+2

flutter:
  uses-material-design: true