name: flutter_curiosity
description: The flutter curiosity is compatible with android and ios for multiple native features
version: 4.2.1
repository: https://github.com/Wayaer/flutter_curiosity.git

environment:
  sdk: '>=2.17.1 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: flutter.curiosity
        pluginClass: CuriosityPlugin
      ios:
        pluginClass: CuriosityPlugin
      macos:
        pluginClass: CuriosityPlugin
      linux:
        pluginClass: CuriosityPlugin
      windows:
        pluginClass: CuriosityPlugin

