name: flutter_curiosity
description: The flutter curiosity is compatible with android and ios for multiple native features
version: 3.3.2
repository: https://github.com/Wayaer/flutter_curiosity.git

environment:
  sdk: '>=2.12.1 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.4

flutter:
  plugin:
    platforms:
      android:
        package: flutter.curiosity
        pluginClass: CuriosityPlugin
      ios:
        pluginClass: CuriosityPlugin
      macos:
        pluginClass: CuriosityPlugin
      linux:
        pluginClass: CuriosityPlugin
      windows:
        pluginClass: CuriosityPlugin

