name: flutter_curiosity
description: A new Flutter plugin about flutter curiosity
version: 0.0.1
author: Wayaer
homepage: https://github.com/Wayaer/flutter-curiosity.git
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  plugin:
    platforms:
      android:
        package: flutter.curiosity
        pluginClass: CuriosityPlugin
#      ios:
#        pluginClass: FLTPathProviderPlugin
#  plugin:
#    androidPackage: flutter.curiosity
#    pluginClass: FlutterCuriosityPlugin
