name: flutter_curiosity
description: The flutter curiosity is compatible with android and ios for multiple native features
version: 1.1.1
author: wayaer <Wayaer@foxmail.com>
homepage: https://github.com/Wayaer/flutter-curiosity.git
environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: flutter.curiosity
        pluginClass: CuriosityPlugin
      ios:
        pluginClass: CuriosityPlugin
    #      macos:
    #        pluginClass: CuriosityPlugin
    #      web:
    #        pluginClass: CuriosityPlugin
    #        fileName: CuriosityPlugin.dart
    environment:
      sdk: ">=2.1.0 <3.0.0"
      flutter: ">=1.12.0 <2.0.0"
