name: flutter_curiosity
description: The flutter curiosity is compatible with android and ios for multiple native features
version: 1.6.0
homepage: https://github.com/Wayaer/flutter_curiosity.git
environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: flutter.curiosity
        pluginClass: CuriosityPlugin
      ios:
        pluginClass: CuriosityPlugin
      macos:
        pluginClass: CuriosityPlugin
      web:
        pluginClass: CuriosityPlugin
        fileName: flutter_curiosity_web.dart
